In [1]:
import pandas as pd
import pandas as read_csv

df = pd.read_csv('retail_store_sales.csv')

In [2]:
print(df.head())

  Transaction ID Customer ID       Category          Item  Price Per Unit  \
0    TXN_6867343     CUST_09     Patisserie   Item_10_PAT            18.5
1    TXN_3731986     CUST_22  Milk Products  Item_17_MILK            29.0
2    TXN_9303719     CUST_02       Butchers   Item_12_BUT            21.5
3    TXN_9458126     CUST_06      Beverages   Item_16_BEV            27.5
4    TXN_4575373     CUST_05           Food   Item_6_FOOD            12.5

   Quantity  Total Spent  Payment Method Location Transaction Date  \
0      10.0        185.0  Digital Wallet   Online       08/04/2024
1       9.0        261.0  Digital Wallet   Online       23/07/2023
2       2.0         43.0     Credit Card   Online       05/10/2022
3       9.0        247.5     Credit Card   Online       07/05/2022
4       7.0         87.5  Digital Wallet   Online       02/10/2022

  Discount Applied
0             True
1             True
2            False
3              NaN
4            False

In [3]:
df.tail()

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,03/09/2023,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,12/08/2022,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,24/08/2024,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,30/12/2023,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,06/08/2022,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.9+ MB

In [5]:
df.columns

Index(['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit',
       'Quantity', 'Total Spent', 'Payment Method', 'Location',
       'Transaction Date', 'Discount Applied'],
      dtype='str')

In [6]:
df.index

RangeIndex(start=0, stop=12575, step=1)

In [7]:
len(df['Customer ID'])

12575

In [8]:
df.iloc[0]

Transaction ID         TXN_6867343
Customer ID                CUST_09
Category                Patisserie
Item                   Item_10_PAT
Price Per Unit                18.5
Quantity                      10.0
Total Spent                  185.0
Payment Method      Digital Wallet
Location                    Online
Transaction Date        08/04/2024
Discount Applied              True
Name: 0, dtype: object

In [9]:
df.head( )

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08/04/2024,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,23/07/2023,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,05/10/2022,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,07/05/2022,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,02/10/2022,False

In [10]:
df.tail( )

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,03/09/2023,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,12/08/2022,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,24/08/2024,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,30/12/2023,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,06/08/2022,NaN

In [11]:
df[df['Category'] == 'Patisserie']

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08/04/2024,True
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,30/11/2023,NaN
13,TXN_4413070,CUST_14,Patisserie,Item_24_PAT,39.5,6.0,237.0,Digital Wallet,In-store,20/05/2022,False
16,TXN_7563311,CUST_23,Patisserie,Item_17_PAT,29.0,8.0,232.0,Cash,Online,16/11/2024,True
29,TXN_7138501,CUST_18,Patisserie,Item_22_PAT,36.5,5.0,182.5,Credit Card,In-store,10/03/2022,False
...,...,...,...,...,...,...,...,...,...,...,...
12520,TXN_7459774,CUST_20,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,Online,25/04/2022,True
12536,TXN_2919179,CUST_23,Patisserie,Item_1_PAT,5.0,7.0,35.0,Digital Wallet,Online,22/11/2022,True
12563,TXN_5394856,CUST_08,Patisserie,Item_17_PAT,29.0,2.0,58.0,Digital Wallet,Online,24/10/2024,True
12569,TXN_2318174,CUST_18,Patisserie,Item_1_PAT,5.0,9.0,45.0,Digital Wallet,In-store,13/05/2024,False
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,03/09/2023,NaN

In [12]:
df[(df['Category'] == 'Patisserie') & (df['Location'] == 'Online')]

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08/04/2024,True
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,30/11/2023,NaN
16,TXN_7563311,CUST_23,Patisserie,Item_17_PAT,29.0,8.0,232.0,Cash,Online,16/11/2024,True
31,TXN_4353295,CUST_22,Patisserie,Item_6_PAT,12.5,8.0,100.0,Credit Card,Online,05/04/2022,True
47,TXN_9331642,CUST_12,Patisserie,Item_11_PAT,20.0,4.0,80.0,Credit Card,Online,06/07/2022,True
...,...,...,...,...,...,...,...,...,...,...,...
12470,TXN_7765690,CUST_25,Patisserie,Item_1_PAT,5.0,1.0,5.0,Cash,Online,03/03/2024,True
12504,TXN_3294780,CUST_19,Patisserie,Item_20_PAT,33.5,4.0,134.0,Credit Card,Online,14/10/2022,True
12520,TXN_7459774,CUST_20,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,Online,25/04/2022,True
12536,TXN_2919179,CUST_23,Patisserie,Item_1_PAT,5.0,7.0,35.0,Digital Wallet,Online,22/11/2022,True
12563,TXN_5394856,CUST_08,Patisserie,Item_17_PAT,29.0,2.0,58.0,Digital Wallet,Online,24/10/2024,True

In [13]:
df[(df['Category'] == 'Patisserie') | (df['Location'] == 'Online')]

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08/04/2024,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,23/07/2023,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,05/10/2022,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,07/05/2022,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,02/10/2022,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,03/09/2023,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,12/08/2022,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,24/08/2024,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,30/12/2023,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,06/08/2022,NaN

In [14]:
df.head

<bound method NDFrame.head of       Transaction ID Customer ID       Category          Item  Price Per Unit  \
0        TXN_6867343     CUST_09     Patisserie   Item_10_PAT            18.5
1        TXN_3731986     CUST_22  Milk Products  Item_17_MILK            29.0
2        TXN_9303719     CUST_02       Butchers   Item_12_BUT            21.5
3        TXN_9458126     CUST_06      Beverages   Item_16_BEV            27.5
4        TXN_4575373     CUST_05           Food   Item_6_FOOD            12.5
...              ...         ...            ...           ...             ...
12570    TXN_9347481     CUST_18     Patisserie   Item_23_PAT            38.0
12571    TXN_4009414     CUST_03      Beverages    Item_2_BEV             6.5
12572    TXN_5306010     CUST_11       Butchers    Item_7_BUT            14.0
12573    TXN_5167298     CUST_04      Furniture    Item_7_FUR            14.0
12574    TXN_2407494     CUST_23           Food   Item_9_FOOD            17.0

       Quantity  Total Spent  Payment Method  Location Transaction Date  \
0          10.0        185.0  Digital Wallet    Online       08/04/2024
1           9.0        261.0  Digital Wallet    Online       23/07/2023
2           2.0         43.0     Credit Card    Online       05/10/2022
3           9.0        247.5     Credit Card    Online       07/05/2022
4           7.0         87.5  Digital Wallet    Online       02/10/2022
...         ...          ...             ...       ...              ...
12570       4.0        152.0     Credit Card  In-store       03/09/2023
12571       9.0         58.5            Cash    Online       12/08/2022
12572      10.0        140.0            Cash    Online       24/08/2024
12573       6.0         84.0            Cash    Online       30/12/2023
12574       3.0         51.0            Cash    Online       06/08/2022

      Discount Applied
0                 True
1                 True
2                False
3                  NaN
4                False
...                ...
12570              NaN
12571            False
12572              NaN
12573             True
12574              NaN

[12575 rows x 11 columns]>

In [15]:
df['Transaction ID']

0        TXN_6867343
1        TXN_3731986
2        TXN_9303719
3        TXN_9458126
4        TXN_4575373
            ...
12570    TXN_9347481
12571    TXN_4009414
12572    TXN_5306010
12573    TXN_5167298
12574    TXN_2407494
Name: Transaction ID, Length: 12575, dtype: str

In [16]:
df.tail( )

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,03/09/2023,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,12/08/2022,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,24/08/2024,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,30/12/2023,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,06/08/2022,NaN

In [17]:
df.info( )

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.9+ MB

In [19]:
df.isnull().sum

<bound method DataFrame.sum of        Transaction ID  Customer ID  Category   Item  Price Per Unit  Quantity  \
0               False        False     False  False           False     False
1               False        False     False  False           False     False
2               False        False     False  False           False     False
3               False        False     False  False           False     False
4               False        False     False  False           False     False
...               ...          ...       ...    ...             ...       ...
12570           False        False     False  False           False     False
12571           False        False     False  False           False     False
12572           False        False     False  False           False     False
12573           False        False     False  False           False     False
12574           False        False     False  False           False     False

       Total Spent  Payment Method  Location  Transaction Date  \
0            False           False     False             False
1            False           False     False             False
2            False           False     False             False
3            False           False     False             False
4            False           False     False             False
...            ...             ...       ...               ...
12570        False           False     False             False
12571        False           False     False             False
12572        False           False     False             False
12573        False           False     False             False
12574        False           False     False             False

       Discount Applied
0                 False
1                 False
2                 False
3                  True
4                 False
...                 ...
12570              True
12571             False
12572              True
12573             False
12574              True

[12575 rows x 11 columns]>

In [20]:

print(df.isnull().sum(axis=1))

0        0
1        0
2        0
3        1
4        0
        ..
12570    1
12571    0
12572    1
12573    0
12574    1
Length: 12575, dtype: int64

In [22]:
 df['Quantity'].fillna(df['Quantity'].mean(), inplace=True)

C:\Users\Savitha N S\AppData\Local\Temp\ipykernel_34492\3279662209.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Quantity'].fillna(df['Quantity'].mean(), inplace=True)

0        10.0
1         9.0
2         2.0
3         9.0
4         7.0
         ...
12570     4.0
12571     9.0
12572    10.0
12573     6.0
12574     3.0
Name: Quantity, Length: 12575, dtype: float64

In [23]:
df['Quantity']

0        10.0
1         9.0
2         2.0
3         9.0
4         7.0
         ...
12570     4.0
12571     9.0
12572    10.0
12573     6.0
12574     3.0
Name: Quantity, Length: 12575, dtype: float64

In [24]:
df

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08/04/2024,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,23/07/2023,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,05/10/2022,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,07/05/2022,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,02/10/2022,False
...,...,...,...,...,...,...,...,...,...,...,...
12570,TXN_9347481,CUST_18,Patisserie,Item_23_PAT,38.0,4.0,152.0,Credit Card,In-store,03/09/2023,NaN
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,12/08/2022,False
12572,TXN_5306010,CUST_11,Butchers,Item_7_BUT,14.0,10.0,140.0,Cash,Online,24/08/2024,NaN
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,30/12/2023,True
12574,TXN_2407494,CUST_23,Food,Item_9_FOOD,17.0,3.0,51.0,Cash,Online,06/08/2022,NaN

In [25]:
df.dropna(inplace=True)

In [26]:
df

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08/04/2024,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,23/07/2023,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,05/10/2022,False
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,02/10/2022,False
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,10/06/2023,True
...,...,...,...,...,...,...,...,...,...,...,...
12566,TXN_6298574,CUST_01,Milk Products,Item_1_MILK,5.0,4.0,20.0,Cash,Online,09/05/2023,False
12567,TXN_4890318,CUST_25,Butchers,Item_3_BUT,8.0,5.0,40.0,Credit Card,In-store,28/03/2023,False
12569,TXN_2318174,CUST_18,Patisserie,Item_1_PAT,5.0,9.0,45.0,Digital Wallet,In-store,13/05/2024,False
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,12/08/2022,False
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,30/12/2023,True

In [28]:
df['Quantity'].value_counts()

Quantity
6.0     797
8.0     784
5.0     782
3.0     779
10.0    778
7.0     760
4.0     745
9.0     733
2.0     720
1.0     701
Name: count, dtype: int64

In [29]:
df.groupby('Category')['Quantity'].sum()

Category
Beverages                             5156.0
Butchers                              5299.0
Computers and electric accessories    5479.0
Electric household essentials         5226.0
Food                                  5316.0
Furniture                             5209.0
Milk Products                         5350.0
Patisserie                            5084.0
Name: Quantity, dtype: float64

In [30]:
df

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08/04/2024,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,23/07/2023,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,05/10/2022,False
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,02/10/2022,False
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,10/06/2023,True
...,...,...,...,...,...,...,...,...,...,...,...
12566,TXN_6298574,CUST_01,Milk Products,Item_1_MILK,5.0,4.0,20.0,Cash,Online,09/05/2023,False
12567,TXN_4890318,CUST_25,Butchers,Item_3_BUT,8.0,5.0,40.0,Credit Card,In-store,28/03/2023,False
12569,TXN_2318174,CUST_18,Patisserie,Item_1_PAT,5.0,9.0,45.0,Digital Wallet,In-store,13/05/2024,False
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,12/08/2022,False
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,30/12/2023,True

In [31]:
df.sort_values(by='Price Per Unit', ascending=False)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
1587,TXN_4005322,CUST_03,Butchers,Item_25_BUT,41.0,2.0,82.0,Cash,Online,15/05/2022,True
1545,TXN_9847074,CUST_05,Food,Item_25_FOOD,41.0,6.0,246.0,Digital Wallet,Online,14/11/2024,False
4780,TXN_3465682,CUST_12,Butchers,Item_25_BUT,41.0,10.0,410.0,Credit Card,In-store,23/07/2024,False
1596,TXN_8522671,CUST_03,Electric household essentials,Item_25_EHE,41.0,6.0,246.0,Credit Card,In-store,01/12/2022,True
10547,TXN_4300165,CUST_15,Beverages,Item_25_BEV,41.0,3.0,123.0,Digital Wallet,Online,18/02/2023,True
...,...,...,...,...,...,...,...,...,...,...,...
497,TXN_5372777,CUST_08,Milk Products,Item_1_MILK,5.0,6.0,30.0,Credit Card,Online,30/05/2022,True
9041,TXN_5189628,CUST_04,Milk Products,Item_1_MILK,5.0,9.0,45.0,Credit Card,In-store,10/04/2024,True
12035,TXN_6038887,CUST_10,Electric household essentials,Item_1_EHE,5.0,7.0,35.0,Credit Card,Online,11/07/2024,False
12028,TXN_2798740,CUST_05,Milk Products,Item_1_MILK,5.0,10.0,50.0,Cash,Online,16/03/2023,True
4959,TXN_2692916,CUST_05,Butchers,Item_1_BUT,5.0,7.0,35.0,Digital Wallet,In-store,30/09/2024,True

In [32]:
df.sort_values(by='Quantity', ascending=False)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
27,TXN_1599706,CUST_14,Furniture,Item_25_FUR,41.0,10.0,410.0,Credit Card,In-store,24/03/2024,True
28,TXN_1598860,CUST_08,Food,Item_14_FOOD,24.5,10.0,245.0,Cash,In-store,23/10/2022,True
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08/04/2024,True
30,TXN_5444504,CUST_05,Food,Item_11_FOOD,20.0,10.0,200.0,Digital Wallet,Online,26/04/2022,False
6309,TXN_2663819,CUST_08,Food,Item_13_FOOD,23.0,10.0,230.0,Credit Card,In-store,31/03/2024,True
...,...,...,...,...,...,...,...,...,...,...,...
1224,TXN_7094868,CUST_20,Furniture,Item_20_FUR,33.5,1.0,33.5,Digital Wallet,Online,07/11/2023,True
23,TXN_3314099,CUST_04,Food,Item_10_FOOD,18.5,1.0,18.5,Cash,Online,30/09/2023,False
6275,TXN_6820010,CUST_19,Milk Products,Item_22_MILK,36.5,1.0,36.5,Digital Wallet,Online,29/09/2024,False
12470,TXN_7765690,CUST_25,Patisserie,Item_1_PAT,5.0,1.0,5.0,Cash,Online,03/03/2024,True
12454,TXN_1384868,CUST_10,Furniture,Item_2_FUR,6.5,1.0,6.5,Credit Card,In-store,27/09/2023,True

In [33]:
df

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,08/04/2024,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,23/07/2023,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,05/10/2022,False
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,02/10/2022,False
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,10/06/2023,True
...,...,...,...,...,...,...,...,...,...,...,...
12566,TXN_6298574,CUST_01,Milk Products,Item_1_MILK,5.0,4.0,20.0,Cash,Online,09/05/2023,False
12567,TXN_4890318,CUST_25,Butchers,Item_3_BUT,8.0,5.0,40.0,Credit Card,In-store,28/03/2023,False
12569,TXN_2318174,CUST_18,Patisserie,Item_1_PAT,5.0,9.0,45.0,Digital Wallet,In-store,13/05/2024,False
12571,TXN_4009414,CUST_03,Beverages,Item_2_BEV,6.5,9.0,58.5,Cash,Online,12/08/2022,False
12573,TXN_5167298,CUST_04,Furniture,Item_7_FUR,14.0,6.0,84.0,Cash,Online,30/12/2023,True

In [34]:
df.to_csv('cleaned_retailsalesdata1.csv', index=False)